blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/jz8T2uahpH
    about: Urgent or blocking issues, quick questions, sharing a video of a bug, or anything that's better as a chat.
